### ISSUE TITLE
The fonts file aren't being included

### ISSUE THREAD

**Issue by evaldosantos** [janklever/licons#12]
You can't use this lib only adding <link rel="stylesheet" href="https://cdn.klever.space/licons/v2.0/licons.min.css" > as described. If you do this, you will get an error saying that .ttf and .wof file aren't included. I have attached an image with this issue on google chrome.

![licons-issue](https://cloud.githubusercontent.com/assets/1689140/16469522/d450b1d6-3e27-11e6-8286-81a89e319d81.png)

**Comment by janklever** [comment]
Thanks, mate... Bug fixed!
