### ISSUE TITLE
search correction

### ISSUE THREAD

**Issue by janklever** [janklever/licons#4]
**Implement the search for all items on the page.**

**Comment by evaldosantos** [comment]
What this empty string do
var result = $(this).text().toUpperCase().indexOf(' '+txt.toUpperCase());
?

**Comment by evaldosantos** [comment]
I've update this part to 
var result = ('LI-' + $(this).find('.ligature input').val().toUpperCase()).indexOf(txt.toUpperCase());
seems worked
